name: PrivateSQL
summary: This is a deployment of private SQL Server with VNet.
description: SQL connected by private link to vnet
templatePath: main.bicep
runner: "bfyoprivateregistery.azurecr.io/ade:1.0.0"
parameters:
- id: "sqlAdministratorLogin"
  type: "string"
  required: true
- id: "sqlAdministratorLoginPassword"
  type: "string"
  required: true
